version : "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ezlearner-network  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - ezlearner-network
    depends_on:
      - prometheus
  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
      - ezlearner-network
  configserver:
    image: priyam569/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - ezlearner-network
    depends_on: 
      - zipkin
    environment:
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/   
  eurekaserver:
    image: priyam569/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - ezlearner-network
    depends_on: 
      - zipkin
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 35s
        max_attempts: 3
        window: 120s
    environment:
       SERVER.PORT: 8070
       SPRING_PROFILES_ACTIVE: default
       SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
       SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
  db:
    image: priyam569/postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - ezlearner-network
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    
  EZLEARNERCOURSES:
    image: priyam569/ezlearnercourses:latest
    mem_limit: 700m
    ports:
      - "8086:8081"
    networks:
      - ezlearner-network
    depends_on: 
      - zipkin
      - configserver
      - eurekaserver
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 55s
        max_attempts: 3
        window: 420s
    environment:
       SPRING_PROFILES_ACTIVE: default
       SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
       EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
       SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
       SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/postgres
       SPRING_DATASOURCE_USERNAME: postgres
       SPRING_DATASOURCE_PASSWORD: postgres
       #SPRING_JPA_HIBERNATE_DDL_AUTO: update
  TUTORS:
    image: priyam569/tutors:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - ezlearner-network
    depends_on: 
      - zipkin
      - configserver
      - eurekaserver
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 55s
        max_attempts: 3
        window: 120s
    environment:
       SERVER.PORT: 8080
       SPRING_PROFILES_ACTIVE: default
       SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
       EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
       SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
       SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/postgres
       SPRING_DATASOURCE_USERNAME: postgres
       SPRING_DATASOURCE_PASSWORD: postgres
  SERVICES:
    image: priyam569/services:latest
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - ezlearner-network
    depends_on: 
      - zipkin
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 55s
        max_attempts: 3
        window: 120s
    environment:
       SERVER.PORT: 8082	 
       SPRING_PROFILES_ACTIVE: default
       SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
       EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
       SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
  APIGATEWAY:
    image: priyam569/apigateway:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - ezlearner-network
    depends_on:
      - zipkin 
      - configserver
      - eurekaserver
      - EZLEARNERCOURSES
      - TUTORS
      - SERVICES
    deploy:
      restart_policy:
        condition: on-failure
        delay: 55s
        max_attempts: 3
        window: 180s
    environment:
       SERVER.PORT: 8072	 
       SPRING_PROFILES_ACTIVE: default
       SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
       EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
       SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
  EZLEARNER:
    image: priyam569/private-ezlearn:0.0.1
    #mem_limit: 700m
    ports:
      - "4200:4200"
    networks:
      - ezlearner-network
    #depends_on:
     # - EZLEARNERCOURSES
     # - TUTORS
     # - SERVICES
    deploy:
      restart_policy:
        condition: on-failure
        delay: 55s
        max_attempts: 3
        window: 180s
  jobmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - ezlearner-network
  taskmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    links:
      - "jobmanager:jobmanager"
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - ezlearner-network
  zookeeper:
    image: priyam569/zookeeper:latest
    expose:
      - "2181"
    networks:
      - ezlearner-network
  serviceconsumer:
    image: priyam569/servicesconsumer
    ports:
      - "8087:8085"
    networks:
      - ezlearner-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 55s
        max_attempts: 3
        window: 180s
  flinkproduceraggregator:
    image: priyam569/flinkproduceraggregator
    ports:
      - "8088:8080"
    networks:
      - ezlearner-network
    depends_on:
      - taskmanager
      - zookeeper
    deploy:
      restart_policy:
        condition: on-failure
        delay: 55s
        max_attempts: 3
        window: 180s
networks:
  ezlearner-network:
volumes:
  db:
    driver: local
