global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'tutors'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['tutors:8080']
  - job_name: 'ezlearnercourses'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ezlearnercourses:8081']
  - job_name: 'services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['services:8082']