version : "3.8"
services:
  configserver:
    image: priyam569/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - ezlearner-network
  eurekaserver:
    image: priyam569/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - ezlearner-network
    depends_on: 
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 35s
        max_attempts: 3
        window: 120s
    environment:
       SPRING_PROFILES_ACTIVE: prod
       SPRING_CONFIG_IMPORT: configserver:http://configserver:8071 	
  services:
    image: priyam569/services:latest
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - ezlearner-network
    depends_on: 
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 55s
        max_attempts: 3
        window: 120s
    environment:
       SPRING_PROFILES_ACTIVE: prod
       SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
       EUREKA_CLIENT_SERVICEURL_prod_ZONE: http://eurekaserver:8070/eureka	
  courses:
    image: priyam569/courses:latest
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - ezlearner-network
    depends_on: 
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 55s
        max_attempts: 3
        window: 120s
    environment:
       SPRING_PROFILES_ACTIVE: prod
       SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
       EUREKA_CLIENT_SERVICEURL_prod_ZONE: http://eurekaserver:8070/eureka		
  tutors:
    image: priyam569/tutors:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - ezlearner-network
    depends_on: 
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 55s
        max_attempts: 3
        window: 120s
    environment:
       SPRING_PROFILES_ACTIVE: prod
       SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
       EUREKA_CLIENT_SERVICEURL_prod_ZONE: http://eurekaserver:8070/eureka
networks:
  ezlearner-network:
